const swaggerUi = require('swagger-ui-express');
const swaggerJsDoc = require('swagger-jsdoc');

const options = {
    swaggerDefinition: {
        swaggerVersion: '2.0',
        info: {
            title: 'Hackaton Data vs Corona virus',
            version: '1.0.0',
            description: 'Hackaton Data vs Corona virus API with autogenerated swagger doc'
        },
        basePath: '/api',
        securityDefinitions: {
            jwt: {
                type: 'apiKey',
                name: 'Authorization',
                in: 'header',
            },
        },
        security: [{ jwt: [] }],
    },
    apis: ['./api/controllers/*.js']
};

const specs = swaggerJsDoc(options);

module.exports = (app) => {
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
};