const swaggerUi = require('swagger-ui-express');
const swaggerJsDoc = require('swagger-jsdoc');

const options = {
    swaggerDefinition: {
        openapi: '3.0.1',
        info: {
            title: 'Hackaton Data vs Corona virus',
            version: '1.0.0',
            description: 'Hackaton Data vs Corona virus API with autogenerated swagger doc'
        },
        basePath: '/api',
        components: {
            securitySchemes: {
                bearerAuth: {
                    type: 'http',
                    scheme: 'bearer',
                    in: 'header',
                    bearerFormat: 'JWT',
                }
            }
        },
        security: [
            {},
            {bearerAuth: []}
        ]
    },
    apis: ['./docs/*.yaml', './api/controllers/*.js']
};

const specs = swaggerJsDoc(options);

module.exports = (app) => {
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
};