const mongoose = require('mongoose');

const patientRelevantDataSchema = mongoose.Schema({
    _id: mongoose.Schema.Types.ObjectId,
    travelToRiskCountriesInTheLast14Days: { type: mongoose.Schema.Types.Mixed, default: null },
    contactInTheLast14DaysWithAPersonWhoHasSymptoms: { type: Boolean, default: null },
    haveYouBeenInContactWithPeopleWhoHaveTheCoronaVirusInTheLast14Days: { type: Boolean, default: null },
    haveYouEverBeenToAHealthCareFacilityWhereTheDiseaseHasBeenDiagnosedWithANewCoronavirus: { type: Boolean, default: null },
    didYouGoForAExaminationSomewhere: { type: Boolean, default: null },
    symptoms: [String],
    symptomsDuration: { type: Number, required: false },
    highTemperature: { type: mongoose.Schema.Types.Mixed, default: null },
    shaking: { type: Boolean, default: null },
    lossOfAppetite: { type: Boolean, default: null },
    exhaustion: { type: Boolean, default: null },
    muscleAchesAndPains: { type: Boolean, default: null },
    boneOrJointPain: { type: Boolean, default: null },
    cough: { type: Boolean, default: null },
    expectoration: { type: Boolean, default: null },
    shortnessOfBreath: { type: Boolean, default: null },
    choking: { type: Boolean, default: null },
    fatigue: { type: Boolean, default: null },
    chestPressure: { type: Boolean, default: null },
    chestPain: { type: Boolean, default: null },
    sneezing: { type: Boolean, default: null },
    nasalCongestion: { type: Boolean, default: null },
    secretionFromTheNose: { type: Boolean, default: null },
    bleedingFromTheNose: { type: Boolean, default: null },
    eyesPain: { type: Boolean, default: null },
    redEyes: { type: Boolean, default: null },
    throatProblems: { type: Boolean, default: null },
    throatSecretion: { type: Boolean, default: null },
    headache: { type: Boolean, default: null },
    abdominalPain: { type: Boolean, default: null },
    nausea: { type: Boolean, default: null },
    vomit: { type: Boolean, default: null },
    diarrhea: { type: Boolean, default: null },
    backPain: { type: Boolean, default: null },
    urinaryProblems: { type: Boolean, default: null },
    rash: { type: Boolean, default: null },
    enlargedLymphNodes: { type: Boolean, default: null },
    neuroInterferences: { type: Boolean, default: null },
    increasedBloodPressure: { type: Boolean, default: null },
    positiveToCoronavirus: { type: Boolean, default: null },
    curedOfCoronavirus: { type: Boolean, default: null }
});

module.exports = mongoose.model('PatientRelevantData', patientRelevantDataSchema);